### ISSUE TITLE
Acronym ADMI in presentations fails pre-commit test

### ISSUE THREAD

**Issue by carlosmalt** [iris-hep/iris-hep.github.io#1406]
The The Association of Computer Science Departments at Minority Institutions (ADMI) organizes a yearly conference called ADMI 2022. I was unable to use the acronym ADMI in my list of presentations since it failed a pre-commit test: codespell thinks it's a typo for "ADMIN". I worked around it by leaving out the acronym. But that's only acceptable as a temporary fix. Many conferences are far better known by their acronym than by what the acronym stands for.

**Comment by henryiii** [comment]
This can be added to the ignore list in `pre-commit-config.yaml` (in lowercase).
