### ISSUE TITLE
Presentations not showing up for some members under "by institution" view

### ISSUE THREAD

**Issue by matthewfeickert** [iris-hep/iris-hep.github.io#1659]
After @cranmer brought up the issue of not being able to have multiple institutions associated with member metadata to accommodate movement between universities. @rct225 added preliminary support for this in PR #1656. While looking at this for PR #1658 I noticed that all of my [presentations visible under when viewing "by person"](https://iris-hep.org/presentations/byperson.html) are **not** visible at all when [viewed "by institution"](https://iris-hep.org/presentations/byinstitution.html). Same goes for @alexander-held's presentations.

**Comment by cranmer** [comment]
@henryiii not sure if this is on your radar. Maybe not that high priority, but...

**Comment by rct225** [comment]
I think I might have a fix.  I tried it with @cranmer @matthewfeickert and @alexander-held (I made up a date for testing, you might want to change it).  I'll making a PR now.  Can you all take a look and see if the proper presentations are there?

**Comment by rct225** [comment]
Reopened until someone can verify the talks are appearing as expected.

**Comment by matthewfeickert** [comment]
I think this is working now @rct225, so I'm going to close this now.
