### ISSUE TITLE
Error in Workflow Run

### ISSUE THREAD

**Issue by rct225** [iris-hep/iris-hep.github.io#1721]
The following error appeared in workflow run, https://github.com/iris-hep/iris-hep.github.io/actions/runs/4501915194 :

/home/runner/work/iris-hep.github.io/iris-hep.github.io/_plugins/getpub.rb:170:in `inspire': Getting 1861935 failed with code 301: MOVED PERMANENTLY (IOError)
[1448](https://github.com/iris-hep/iris-hep.github.io/actions/runs/4501915194/jobs/7922993510#step:6:1449)

**Comment by henryiii** [comment]
`1861935` seems to have moved to `2632195`: https://inspirehep.net/literature/1861935 redirects to https://inspirehep.net/literature/2632195
