### ISSUE TITLE
how to add papers to individual data

### ISSUE THREAD

**Issue by cranmer** [iris-hep/iris-hep.github.io#18]
I only see presentations in the template
https://github.com/iris-hep/iris-hep.github.io/blob/master/_data/people/cranmer.yml

**Comment by pelmer** [comment]
That is because there are zero presentations in your file. Take a look at pelmer.yml for the expected format.

**Comment by cranmer** [comment]
Huh? I have 7 presentations in my file. My question is how to add papers, not presentations.

**Comment by pelmer** [comment]
Ah, that we have not yet worked out. Unlike presentations, papers are not associated (typically) to only a single person. So my thought was to just have a yaml data file per paper, but that has not been set up. (Presentations seemed like the more pressing issue for IRIS-HEP at this point.) If you have a proposal as to how to organize that most effectively, it is welcome.

**Comment by henryiii** [comment]
Should be done. Publications can be added, either explicitly or via Inspire.
