### ISSUE TITLE
Fellows page has huge images

### ISSUE THREAD

**Issue by tunnell** [iris-hep/iris-hep.github.io#2191]
While loading it from HSF-India event, I am still waiting to load because the team page is 50 MB.  Please use OpenCV or some other thumbnail tool to make 'small' versions of images.

`tunnell@fried:~/iris-hep.github.io/assets/images/team$ du -sch * | grep M
64K	Aaron-Moate.png
1.2M	Ana-Peixoto.JPG
128K	Carlos-Maltzahn.png
1.4M	Dan-Riley.JPG
112K	Esmaeil-Mirvakili.png
24K	Evan-Massaro.jpg
4.2M	fellows-2020
9.5M	fellows-2021
4.1M	fellows-2022
1.5M	fellows-2023
32K	Heiko-Mueller.jpg
40K	Ketan-Mahajan.jpg
1012K	Manasvi-Goyal.jpg
20K	Marc-Weinberg.jpg
12K	Marian_Stahl.jpg
72K	Marian-Zvada.jpg
40K	Mario-Masciovecchio.jpg
116K	Mark-Neubauer.png
52K	Markus-Atkinson.png
28K	Markus-Klute.jpg
32K	Mason-Proffitt.jpg
4.0K	Matevz-Tadel.jpg
148K	Mat-Selmeci.png
1.3M	Maureen-Carothers.JPG
12K	Michael-Johnson.jpg
284K	Michael-Peters.jpg
120K	Mike-Hildreth.jpg
68K	Mike_Norman.jpg
120K	Mike-Sokoloff.jpg
36K	Mike-Williams.jpg
20K	Mohamed-Elashri.jpeg
2.0M	ncsmith.png
3.8M	Oksana-Shadura.JPG
24K	Sebastian-Macaluso.jpg
76K	Shawn-McKee.jpg
112K	Sudhir-Malik.png
1.8M	Thomas-Boettcher.jpg
46M	total`

**Comment by davidlange6** [comment]
@rct225 could you have a look at this
