### ISSUE TITLE
Automatically delete head branches 

### ISSUE THREAD

**Issue by matthewfeickert** [iris-hep/iris-hep.github.io#334]
Can we please enable automatic deletion of PR head branches in the repo Settings, so that we don't have to manually delete them after each PR?

Should look like this (except that it is unchecked):
![delete_head_branches](https://user-images.githubusercontent.com/5142394/83075859-2d7dfc00-a03a-11ea-806a-50945adfc213.png)

**Comment by henryiii** [comment]
Oops, usually remember to check that...

**Comment by henryiii** [comment]
It's already checked, actually.

**Comment by matthewfeickert** [comment]
> It's already checked, actually.

Ah, sorry I'm being a dummy. I thought that the original project controlled this behavior for the _forks_ as well. I now see that this is on an individual repo basis, so I have to control this for my own fork.
