### ISSUE TITLE
Sorting fellows by date

### ISSUE THREAD

**Issue by rct225** [iris-hep/iris-hep.github.io#346]
Currently the listing of fellows on the main IRIS-HEP page and the fellows page ( https://iris-hep.org/fellows.html ) seem to be sorted alphabetically by title .  Can we change the order so they are listed by start date - "newest" fellows first?

**Comment by henryiii** [comment]
The dates are not currently parsed or even in a standard format.

**Comment by rct225** [comment]
Yes.  I figured that would be an issue.  Perhaps we should standardize the dates.

This is not a huge issue right now, just something that was mentioned.  Not something we should burn many cycles over by any means.  Let's just keep it open for now as a reminder.
