### ISSUE TITLE
Line feed in project_goal for fellows page

### ISSUE THREAD

**Issue by rct225** [iris-hep/iris-hep.github.io#350]
A student submitted a pull request that initially seemed ok as far as format.  It passed through the usual checks as well.  However, the page never appeared on the site.  After some investigation is seems that the extra line feeds in the project_goal caused an issue.  It was not obvious at first when I looked at the file.  The only clue I had that something was amiss was when I viewed the markdown file in the github repo, it did not appear "formatted" as the other fellows' markdown files.

You can see the changes I made here:
[https://github.com/iris-hep/iris-hep.github.io-source/commit/ae1b3d53ea2c196a0ebfd3f58bb33efcbf64b683](https://github.com/iris-hep/iris-hep.github.io-source/commit/ae1b3d53ea2c196a0ebfd3f58bb33efcbf64b683)

**Comment by davidlange6** [comment]
Had the integration checks passed successfully on the original pr?


On 9 Jun 2020, at 19:24, Rob Tuck <notifications@github.com> wrote:

﻿

A student submitted a pull request that initially seemed ok as far as format. It passed through the usual checks as well. However, the page never appeared on the site. After some investigation is seems that the extra line feeds in the project_goal caused an issue. It was not obvious at first when I looked at the file. The only clue I had that something was amiss was when I viewed the markdown file in the github repo, it did not appear "formatted" as the other fellows' markdown files.

You can see the changes I made here:
ae1b3d5<https://github.com/iris-hep/iris-hep.github.io-source/commit/ae1b3d53ea2c196a0ebfd3f58bb33efcbf64b683>

**Comment by rct225** [comment]
It looked to me like it had successfully passed the checks on the original pr.

**Comment by henryiii** [comment]
New lines are valid as long as they are indented. The two lines that were not indented is what broke the page.

The CI can't tell if a page shows up or not, just if it built correctly. I'm not sure what this "raw" blocks would parse as.

**Comment by henryiii** [comment]
(That is, if we know what it parses as when broken, we could add a check for it)

**Comment by rct225** [comment]
Oh OK.  It was the lack of indentation.  It was just conjecture on my part about the line feeds.  Though I could see how a user could miss adding the indentation.

That's a good point about checking for it if we knew how it parsed.  

It did seem like GitHub didn't recognize the file as Markdown with the original block, if that helps.  Unfortunately, the only symptom I could see is that the fellows entry wasn't showing up and the correspond html page didn't appear either.

**Comment by henryiii** [comment]
This would be nice to check. What happens is that if this does not parse as valid YAML, in-between the dual `---`, then it just gets parsed as markdown. Since we are often setting the page title, it might not even show up where it is supposed to be, and it won't have any front matter, so most uses of it in lists and such will go away.

Not sure how to really check this, though; front matter is optional. Maybe something like this: https://github.com/Sankra/jekyll-yaml-front-matter-analyser, or a YAML linter, or manual Ruby code checking each page.
