### ISSUE TITLE
sort team?

### ISSUE THREAD

**Issue by danielskatz** [iris-hep/iris-hep.github.io#4]
It would be nice to sort the team, maybe alphabetically by surname or first name.

**Comment by pelmer** [comment]
This is partially done, in that it now at least shows people university by university, with the universities now in alphabetical order. Not quite what you asked for, but better than random order generated previously every time the website was regenerated.

**Comment by pelmer** [comment]
Given the two-level structure of the underlying data files for the universities and people a bit more jekyll/liquid gymnastics  will be required to sort properly over people's names.

**Comment by henryiii** [comment]
This is now done, with a way to toggle and sub-sorting. See #139.
