### ISSUE TITLE
Issues with Copying Deployment

### ISSUE THREAD

**Issue by tosin-da-glitch** [iris-hep/iris-hep.github.io#562]
Hello, I am using your website to set up the DANCEOrg website, but I am running into some issues with deployment. (https://github.com/DANCEOrg/iris-hep.github.io-source) 

Help would be thoroughly appreciated, and I would be glad to contribute if that would be useful.  

The step that is failing is the "Check RuboCop" step. I checked the permissions for the get_indico.rb and it returned that it has rwx. Also, not sure why the Assignment Branch Condition size for inspire is too high for our code but was not for yours since our code is the same. 
```
Offenses:

_plugins/getpub.rb:129:5: C: Metrics/AbcSize: Assignment Branch Condition size for inspire is too high. [<23, 49, 20> 57.71/55]
    def inspire(pub) ...
    ^^^^^^^^^^^^^^^^
_scripts/get_indico.rb:1:1: W: Lint/ScriptPermission: Script file get_indico.rb doesn't have execute permission.
#!/usr/bin/env ruby
^^^^^^^^^^^^^^^^^^^
```

**Comment by henryiii** [comment]
Sorry, I completely missed this. Do yo still need help? I've moved get_indico to a separate published Ruby module, though getpub is still local. Not sure why you would have issues with this, these checks are relaxed by `.rubocop.yaml`, in the source.

**Comment by tosin-da-glitch** [comment]
Hello, thank you for replying. Our team has decided to move to a different method.
Thank you again.
