### ISSUE TITLE
Presentations filtered by person does not resolve shortname to name

### ISSUE THREAD

**Issue by matthewfeickert** [iris-hep/iris-hep.github.io#563]
I've noticed that if you [view the list of presentations filtered by person](https://iris-hep.org/presentations/byperson.html) that the `shortname` fields do not get resolved to `name` fields as is done with by area, by institution, by date.

Example:

https://github.com/iris-hep/iris-hep.github.io-source/blob/6c42194f1cc0c93ed25a90a48336684e91e6a6e9/_data/people/matthewfeickert.yml#L2

should get resolved to

https://github.com/iris-hep/iris-hep.github.io-source/blob/6c42194f1cc0c93ed25a90a48336684e91e6a6e9/_data/people/matthewfeickert.yml#L1

but in the below screenshot it does not

![shortname_not_expanded](https://user-images.githubusercontent.com/5142394/104682999-9c888d80-56bb-11eb-9d13-e4aa2450c8f6.png)

**Comment by henryiii** [comment]
Fixed in #605 some time ago.
