### ISSUE TITLE
Update XCache Project Page

### ISSUE THREAD

**Issue by bbockelm** [iris-hep/iris-hep.github.io#669]
Please review the contents of the XCache project page here: https://iris-hep.org/projects/caching.html

Try to have the following
- [x] Project description is up-to-date and reflects the current status of the project.
- [x] One or two figures explaining the architecture of the project and scale / performance results (such as screenshots from monitoring or a figure reproduced from a figure), as applicable.
- [x] Recent accomplishments (particularly if they are checking off an NSF milestone) and plans / research directions for the next year or so.
- [x] Team section has all the right people listed.
- [x] All relevant papers are listed under publications.  Papers should acknowledge IRIS-HEP.
- [x] All relevant presentations are uploaded.  Presentations should acknowledge IRIS-HEP.

**Comment by bbockelm** [comment]
@ddavila0 @fkw888 - what's the latest here?  Frank had a number of good suggestions in email but I was hoping to see a draft by yesterday.

**Comment by ddavila0** [comment]
Just created the PR: https://github.com/iris-hep/iris-hep.github.io-source/pull/761
@bbockelm or @fkw888  could you merge it please?

**Comment by bbockelm** [comment]
#761 solved this issue.
