### ISSUE TITLE
Team page not being built on deploy

### ISSUE THREAD

**Issue by matthewfeickert** [iris-hep/iris-hep.github.io#86]
# Description

Today @msneubauer added the YAML for a new entry to the team page (me) (c.f. https://github.com/iris-hep/iris-hep.github.io/commit/abda6c8716be347ea735d37faff30c791b45d472) which we can see from the [commit history](https://github.com/iris-hep/iris-hep.github.io/commits/master) that GitHub pages successfully deployed. However, the [Full Team page](http://iris-hep.org/about/team) isn't updating.

I haven't attempted to build the page locally and see how it looks, and won't have time for the rest of the week, but if someone has thoughts on this it would be good to fix and then see if checks can be added in the future for page deployment. (@pelmer as it seems that you've done [most dev work](https://github.com/iris-hep/iris-hep.github.io/graphs/contributors) on the site maybe you have thoughts for things to poke here)  Maybe something like [Netlify](http://netlify.com) as it seems to be nicer deployment testing then [ReadTheDocs](https://readthedocs.org/).

**Comment by pelmer** [comment]
That is because he only added the yaml for you as a person, but didn't add you to the file for the institution (UIUC). The people files are used for more than just the team, e.g. the advisory board, so you have to be added also to the institution file.

**Comment by pelmer** [comment]
Go ahead and submit a pull request for that change, too.

**Comment by matthewfeickert** [comment]
Thanks for your help @pelmer! :+1:
