### ISSUE TITLE
Add check of personnel file match to institutional file

### ISSUE THREAD

**Issue by matthewfeickert** [iris-hep/iris-hep.github.io#88]
# Description

As @henryiii [pointed out](https://github.com/iris-hep/iris-hep.github.io/pull/87#issuecomment-506146353), a test can be added (maybe even as a pre-commit hook?) to follow up his PR #83 to check that every person listed in an individual person YAML file also has their `shortname` listed in an institution personnel listing YAML file.

I don't know Ruby or I would add it myself right now, but if no one beats me to it I could take a stab at it when I've finished my thesis (in a few weeks).

**Comment by henryiii** [comment]
Some people are not supposed to be listed in an institution as well - like SB members. However, there should probably be a `fullteam: false` or something like that allowing checks like this.

**Comment by henryiii** [comment]
This is done, actually, as of #238, with `hidden: true`.
