### ISSUE TITLE
sort the presentation by area list

### ISSUE THREAD

**Issue by davidlange6** [iris-hep/iris-hep.github.io#95]
hi @henryiii 

could you also sort the presentations (eg, by area) by date (so the list of AS presentations would start with the latest one)? This requires an extra loop and a sort a la

https://github.com/iris-hep/iris-hep.github.io/blob/master/_includes/get_pres_list.html

**Comment by pelmer** [comment]
The bymonth and byinstitution pages have the same (outstanding) issue. Within each given month or institution, the presentations should be sorted (latest first) by date. David's sorting trick for the accumulated list should work in those cases, too, I think.
