### ISSUE TITLE
Modified publication didn't update on webpage

### ISSUE THREAD

**Issue by cranmer** [iris-hep/iris-hep.github.io#964]
Hi… something went funky here with PR #961 

See 
https://github.com/iris-hep/iris-hep.github.io-source/pull/961/files
you see the `related-work: true` was removed and the citation was changed. But the website didn’t update properly.

Current version of file:
https://github.com/iris-hep/iris-hep.github.io-source/blob/master/_data/publications/1864766.yml

But the publication still shows up in related work section with old citation information. Caching?

**Comment by matthewfeickert** [comment]
@cranmer I reran the CI and it passed and deployed now. What I saw before I restarted the CI was that there was a mistmatch between git revs, so I think it was just a problem with internal state.
